# 1,660,820 clt
# Configuration file of Kuiper training experiment

# ========== Cluster configuration ==========
# ip address of the parameter server (need 1 GPU)

ps_ip: h1.bench.gaia-pg0.clemson.cloudlab.us

# ip address of each worker:# of gpus on this worker
worker_ips:
    - h1.bench.gaia-pg0.clemson.cloudlab.us:[2,2] # worker_ip: # of gpus

exp_path: $HOME/FedScale/core

# Entry function of executor and aggregator under $exp_path
executor_entry: executor.py

aggregator_entry: aggregator.py

auth:
    ssh_user: "JIACHEN"
    ssh_private_key: ""

# cmd to run before we can indeed run kuiper (in order)
setup_commands:
    - source /users/JIACHEN/anaconda3/bin/activate fedscale
    - export NCCL_SOCKET_IFNAME='enp94s0f0'         # Run "ifconfig" to ensure the right NIC for nccl if you have multiple NICs

# ========== Additional job configuration ==========
# Default parameters are specified in argParser.py, wherein more description of the parameter can be found

job_conf:
    - log_path: $HOME/FedScale/core/evals # Path of log files
    - job_name: reddit_yogi                # Generate logs under this folder: log_path/job_name/time_stamp
    - total_worker: 200                     # Number of participants per round, we use K=100 in our paper, large K will be much slower
    - data_set: blog                     # Dataset: openImg, google_speech, stackoverflow
    - data_dir: /users/JIACHEN/FedScale/dataset/data/reddit
    - data_map_file: /users/JIACHEN/FedScale/dataset/data/reddit/client_data_mapping/train.csv      # Allocation of data to each client, turn to iid setting if not provided
    - device_conf_file: /users/JIACHEN/FedScale/dataset/data/device_info/client_device_capacity  # Path of the client trace
    - device_avail_file: $HOME/FedScale/dataset/data/device_info/client_behave_trace
    - model: albert-base-v2
    - gradient_policy: fed-yogi                 # {"fed-yogi", "fed-prox", "fed-avg"}, "fed-avg" by default
    - eval_interval: 5                     # How many rounds to run a testing on the testing set
    - epochs: 1000
    - num_loaders: 8
    - batch_size: 16
    - test_bsz: 16
    - task: nlp
    - test_ratio: 0.2
    - learning_rate: 5e-5
    - min_learning_rate: 1e-6
    - local_steps: 10
