ps_ip: h1.fed.gaia-pg0.clemson.cloudlab.us
  
# ip address of each worker:# of gpus on this worker
worker_ips:
    - h1.fed.gaia-pg0.clemson.cloudlab.us:[4,6] # worker_ip: # of gpus
    - h2.fed.gaia-pg0.clemson.cloudlab.us:[6,6] # worker_ip: # of gpus
    - h3.fed.gaia-pg0.clemson.cloudlab.us:[6,6] # worker_ip: # of gpus

exp_path: $HOME/FedScale/core

# Entry function of executor and aggregator under $exp_path
executor_entry: executor.py

aggregator_entry: aggregator.py

auth:
    ssh_user: "JIACHEN"
    ssh_private_key: ""


# cmd to run before we can indeed run kuiper (in order)
setup_commands:
    - source /users/JIACHEN/anaconda3/bin/activate fedscale    
    - export NCCL_SOCKET_IFNAME="enp94s0f0"    

# ========== Additional job configuration ========== 
# Default parameters are specified in argParser.py, wherein more description of the parameter can be found

job_conf: 
    - log_path: $HOME/FedScale/core/evals # Path of log files
    - job_name: speech_prox                # Generate logs under this folder: log_path/job_name/time_stamp
    - total_worker: 100                      # Number of participants per round, we use K=100 in our paper, large K will be much slower
    - task: speech
    - data_set: google_speech                     # Dataset: openImg, google_speech, stackoverflow
    - data_dir: /users/JIACHEN/FedScale/dataset/data/google_speech    # Path of the dataset
    - data_map_file: /users/JIACHEN/FedScale/dataset/data/google_speech/client_data_mapping/train.csv         # Allocation of data to each client, turn to iid setting if not provided
    - device_conf_file: /users/JIACHEN/FedScale/dataset/data/device_info/client_device_capacity    # Path of the client trace
    - device_avail_file: $HOME/FedScale/dataset/data/device_info/client_behave_trace
    - sample_mode: random                                  # Client selection: random, kuiper
    - model: resnet34                            # Models: shufflenet_v2_x2_0, mobilenet_v2, resnet34, albert-base-v2
    - gradient_policy: fed-prox                 # Commenting out this line will turn to "Fedprox"
    - round_penalty: 2.0                    # Penalty factor in our paper (\alpha), \alpha -> 0 turns to (Kuiper w/o sys)
    - eval_interval: 10                     # How many rounds to run a testing on the testing set
    - epochs: 1000                           # Number of rounds to run this training. We use 1000 in our paper, while it may converge w/ ~400 rounds
    - test_bsz: 10
    - pacer_delta: 30                       # Set to include the next WxK clients
    - filter_less: 16                       # Remove clients w/ less than 16 samples
    - batch_size: 16
    - decay_epoch: 15
    - round_threshold: 30                   # the first W * K
    - cut_off_util: 0.4   
